//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConsoleUiCtrlBlock
{
	public virtual ConsoleUiConfig ConsoleUiConfig
	{
		get;
		set;
	}

	public virtual void IteractOnce()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetUserCmd()
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetUserInputString()
	{
		throw new System.NotImplementedException();
	}

	public virtual void SetConfig(ConsoleUiConfig cfg)
	{
		throw new System.NotImplementedException();
	}

	public virtual ConsoleUiConfig GetConfig()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Deactive()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Active()
	{
		throw new System.NotImplementedException();
	}

}

