//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConsoleUiConfig
{
	public virtual void operator=(ConsoleUiConfig cfg)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Set(ConsoleUiConfig cfg)
	{
		throw new System.NotImplementedException();
	}

	public virtual ConsoleUiConfig Get()
	{
		throw new System.NotImplementedException();
	}

}

